export const BRAND_CONFIG = {
  name: "KalaStock",
  tagline: "Create faster. Design better.",
  positioning: "Premium templates and creative assets made for Indian creators, brands, and businesses.",
  announcement: "New: Explore premium festival templates and creative bundles.",
  currency: "₹",
  currencyCode: "INR",
  supportEmail: "support@kalastock.in",
  supportPhone: "+91 98765 43210",
  socials: {
    instagram: "https://instagram.com/kalastock",
    twitter: "https://twitter.com/kalastock",
    youtube: "https://youtube.com/kalastock",
    behance: "https://behance.net/kalastock",
  },
  colors: {
    background: "#F8FAFC",
    surface: "#FFFFFF",
    primaryText: "#0F172A",
    secondaryText: "#64748B",
    primary: "#6D28D9",
    primaryHover: "#5B21B6",
    secondaryAccent: "#06B6D4",
    success: "#10B981",
    error: "#EF4444",
    border: "#E2E8F0",
    darkFooter: "#0F172A",
  },
  categories: [
    "Social Media",
    "Festival Designs",
    "Business",
    "Wedding",
    "Food & Restaurant",
    "YouTube",
    "Presentations",
    "Illustrations",
    "Icons",
    "Backgrounds",
  ],
  popularSearches: [
    "Instagram Post",
    "Independence Day",
    "Wedding",
    "Restaurant",
    "Business",
    "YouTube Thumbnail",
  ],
};
